<?php
namespace Rebel\BCApi2\Entity\SalesQuote;

class Properties
{
    public const id = 'id';
    public const number = 'number';
    public const externalDocumentNumber = 'externalDocumentNumber';
    public const documentDate = 'documentDate';
    public const postingDate = 'postingDate';
    public const dueDate = 'dueDate';
    public const customerId = 'customerId';
    public const customerNumber = 'customerNumber';
    public const customerName = 'customerName';
    public const billToName = 'billToName';
    public const billToCustomerId = 'billToCustomerId';
    public const billToCustomerNumber = 'billToCustomerNumber';
    public const shipToName = 'shipToName';
    public const shipToContact = 'shipToContact';
    public const sellToAddressLine1 = 'sellToAddressLine1';
    public const sellToAddressLine2 = 'sellToAddressLine2';
    public const sellToCity = 'sellToCity';
    public const sellToCountry = 'sellToCountry';
    public const sellToState = 'sellToState';
    public const sellToPostCode = 'sellToPostCode';
    public const billToAddressLine1 = 'billToAddressLine1';
    public const billToAddressLine2 = 'billToAddressLine2';
    public const billToCity = 'billToCity';
    public const billToCountry = 'billToCountry';
    public const billToState = 'billToState';
    public const billToPostCode = 'billToPostCode';
    public const shipToAddressLine1 = 'shipToAddressLine1';
    public const shipToAddressLine2 = 'shipToAddressLine2';
    public const shipToCity = 'shipToCity';
    public const shipToCountry = 'shipToCountry';
    public const shipToState = 'shipToState';
    public const shipToPostCode = 'shipToPostCode';
    public const shortcutDimension1Code = 'shortcutDimension1Code';
    public const shortcutDimension2Code = 'shortcutDimension2Code';
    public const currencyId = 'currencyId';
    public const currencyCode = 'currencyCode';
    public const paymentTermsId = 'paymentTermsId';
    public const shipmentMethodId = 'shipmentMethodId';
    public const salesperson = 'salesperson';
    public const discountAmount = 'discountAmount';
    public const totalAmountExcludingTax = 'totalAmountExcludingTax';
    public const totalTaxAmount = 'totalTaxAmount';
    public const totalAmountIncludingTax = 'totalAmountIncludingTax';
    public const status = 'status';
    public const sentDate = 'sentDate';
    public const validUntilDate = 'validUntilDate';
    public const acceptedDate = 'acceptedDate';
    public const lastModifiedDateTime = 'lastModifiedDateTime';
    public const phoneNumber = 'phoneNumber';
    public const email = 'email';
    public const customer = 'customer';
    public const dimensionValue = 'dimensionValue';
    public const currency = 'currency';
    public const paymentTerm = 'paymentTerm';
    public const shipmentMethod = 'shipmentMethod';
    public const dimensionSetLines = 'dimensionSetLines';
    public const salesQuoteLines = 'salesQuoteLines';
    public const pdfDocument = 'pdfDocument';
    public const attachments = 'attachments';
    public const documentAttachments = 'documentAttachments';
}
