<?php
namespace Rebel\BCApi2\Entity\SalesShipment;

enum Properties
{
    case id;
    case number;
    case externalDocumentNumber;
    case invoiceDate;
    case postingDate;
    case dueDate;
    case customerPurchaseOrderReference;
    case customerId;
    case customerNumber;
    case customerName;
    case billToCustomerId;
    case billToName;
    case billToCustomerNumber;
    case shipToName;
    case shipToContact;
    case sellToAddressLine1;
    case sellToAddressLine2;
    case sellToCity;
    case sellToCountry;
    case sellToState;
    case sellToPostCode;
    case billToAddressLine1;
    case billToAddressLine2;
    case billToCity;
    case billToCountry;
    case billToState;
    case billToPostCode;
    case shipToAddressLine1;
    case shipToAddressLine2;
    case shipToCity;
    case shipToCountry;
    case shipToState;
    case shipToPostCode;
    case currencyCode;
    case orderNumber;
    case paymentTermsCode;
    case shipmentMethodCode;
    case salesperson;
    case pricesIncludeTax;
    case lastModifiedDateTime;
    case phoneNumber;
    case email;
    case customer;
    case salesShipmentLines;
    case dimensionSetLines;
}
