<?php
namespace Rebel\BCApi2\Entity\SalesCreditMemo;

class Properties
{
    public const id = 'id';
    public const number = 'number';
    public const externalDocumentNumber = 'externalDocumentNumber';
    public const creditMemoDate = 'creditMemoDate';
    public const postingDate = 'postingDate';
    public const dueDate = 'dueDate';
    public const customerId = 'customerId';
    public const customerNumber = 'customerNumber';
    public const customerName = 'customerName';
    public const billToName = 'billToName';
    public const billToCustomerId = 'billToCustomerId';
    public const billToCustomerNumber = 'billToCustomerNumber';
    public const sellToAddressLine1 = 'sellToAddressLine1';
    public const sellToAddressLine2 = 'sellToAddressLine2';
    public const sellToCity = 'sellToCity';
    public const sellToCountry = 'sellToCountry';
    public const sellToState = 'sellToState';
    public const sellToPostCode = 'sellToPostCode';
    public const billToAddressLine1 = 'billToAddressLine1';
    public const billToAddressLine2 = 'billToAddressLine2';
    public const billToCity = 'billToCity';
    public const billToCountry = 'billToCountry';
    public const billToState = 'billToState';
    public const billToPostCode = 'billToPostCode';
    public const shortcutDimension1Code = 'shortcutDimension1Code';
    public const shortcutDimension2Code = 'shortcutDimension2Code';
    public const currencyId = 'currencyId';
    public const currencyCode = 'currencyCode';
    public const paymentTermsId = 'paymentTermsId';
    public const shipmentMethodId = 'shipmentMethodId';
    public const salesperson = 'salesperson';
    public const pricesIncludeTax = 'pricesIncludeTax';
    public const discountAmount = 'discountAmount';
    public const discountAppliedBeforeTax = 'discountAppliedBeforeTax';
    public const totalAmountExcludingTax = 'totalAmountExcludingTax';
    public const totalTaxAmount = 'totalTaxAmount';
    public const totalAmountIncludingTax = 'totalAmountIncludingTax';
    public const status = 'status';
    public const lastModifiedDateTime = 'lastModifiedDateTime';
    public const invoiceId = 'invoiceId';
    public const invoiceNumber = 'invoiceNumber';
    public const phoneNumber = 'phoneNumber';
    public const email = 'email';
    public const customerReturnReasonId = 'customerReturnReasonId';
    public const customer = 'customer';
    public const dimensionValue = 'dimensionValue';
    public const currency = 'currency';
    public const paymentTerm = 'paymentTerm';
    public const shipmentMethod = 'shipmentMethod';
    public const customerReturnReason = 'customerReturnReason';
    public const dimensionSetLines = 'dimensionSetLines';
    public const salesCreditMemoLines = 'salesCreditMemoLines';
    public const pdfDocument = 'pdfDocument';
    public const attachments = 'attachments';
    public const documentAttachments = 'documentAttachments';
}
