<?php
namespace Rebel\BCApi2\Entity\PurchaseOrder;

class Properties
{
    public const id = 'id';
    public const number = 'number';
    public const orderDate = 'orderDate';
    public const postingDate = 'postingDate';
    public const vendorId = 'vendorId';
    public const vendorNumber = 'vendorNumber';
    public const vendorName = 'vendorName';
    public const payToName = 'payToName';
    public const payToVendorId = 'payToVendorId';
    public const payToVendorNumber = 'payToVendorNumber';
    public const shipToName = 'shipToName';
    public const shipToContact = 'shipToContact';
    public const buyFromAddressLine1 = 'buyFromAddressLine1';
    public const buyFromAddressLine2 = 'buyFromAddressLine2';
    public const buyFromCity = 'buyFromCity';
    public const buyFromCountry = 'buyFromCountry';
    public const buyFromState = 'buyFromState';
    public const buyFromPostCode = 'buyFromPostCode';
    public const payToAddressLine1 = 'payToAddressLine1';
    public const payToAddressLine2 = 'payToAddressLine2';
    public const payToCity = 'payToCity';
    public const payToCountry = 'payToCountry';
    public const payToState = 'payToState';
    public const payToPostCode = 'payToPostCode';
    public const shipToAddressLine1 = 'shipToAddressLine1';
    public const shipToAddressLine2 = 'shipToAddressLine2';
    public const shipToCity = 'shipToCity';
    public const shipToCountry = 'shipToCountry';
    public const shipToState = 'shipToState';
    public const shipToPostCode = 'shipToPostCode';
    public const shortcutDimension1Code = 'shortcutDimension1Code';
    public const shortcutDimension2Code = 'shortcutDimension2Code';
    public const currencyId = 'currencyId';
    public const currencyCode = 'currencyCode';
    public const pricesIncludeTax = 'pricesIncludeTax';
    public const paymentTermsId = 'paymentTermsId';
    public const shipmentMethodId = 'shipmentMethodId';
    public const purchaser = 'purchaser';
    public const requestedReceiptDate = 'requestedReceiptDate';
    public const discountAmount = 'discountAmount';
    public const discountAppliedBeforeTax = 'discountAppliedBeforeTax';
    public const totalAmountExcludingTax = 'totalAmountExcludingTax';
    public const totalTaxAmount = 'totalTaxAmount';
    public const totalAmountIncludingTax = 'totalAmountIncludingTax';
    public const fullyReceived = 'fullyReceived';
    public const status = 'status';
    public const lastModifiedDateTime = 'lastModifiedDateTime';
    public const vendor = 'vendor';
    public const dimensionValue = 'dimensionValue';
    public const currency = 'currency';
    public const paymentTerm = 'paymentTerm';
    public const shipmentMethod = 'shipmentMethod';
    public const purchaseOrderLines = 'purchaseOrderLines';
    public const attachments = 'attachments';
    public const dimensionSetLines = 'dimensionSetLines';
    public const documentAttachments = 'documentAttachments';
}
